### ISSUE TITLE
Start script works with pre-release jupyter only

### ISSUE THREAD

**Issue by ankostis** [ian-r-rose/binder-workspace-demo#1]
## Versions:
```
ipython==7.5.0
ipython-genutils==0.2.0
jupyter-client==5.2.4
jupyter-core==4.4.0
jupyterhub==1.0.0
jupyterlab==0.35.4
jupyterlab-server==0.2.0
nteract-on-jupyter==2.0.12
python-dateutil==2.8.0
python-editor==1.0.4
```

## Problems
The suggested [`binder/start` script](https://github.com/ian-r-rose/binder-workspace-demo/blob/98acb31e32323d4294f93928a783d914aa25fba6/binder/start#L1) does not work, because:
- The `jupyter lab workspace import` does not have the `--name` option.
- Probably it does not work untill jupyterlab/jupyterlab#5977 make it into a new release.

## Suggestion
Probably, after 5977 has been fixed, the import can happen on build-time, and move the import command in `/binder/postBuild' script.

**Comment by ian-r-rose** [comment]
Please consider your tone when posting issues.

This start script does work, and you can verify it by clicking on the binder link. The `--name` option was added after JupyterLab 0.35 and is available in the 1.0 prerelease series. Once   jupyterlab/jupyterlab#5977 has been released and the dust has settled a bit, I will update the script accordingly.

**Comment by ankostis** [comment]
- Thank you for your prompt reply.
- My apologies for the tone, things like this can escape you, 
  when you're in a hurry to share what you have discovered.
- Indeed,  i must have missed the note in the documentation explaining the pre-release pinning of `jupyterlab==1.0.0a1`.

**Comment by ian-r-rose** [comment]
Sorry to be a bit brusque @ankostis! Yes, this uses 1.0.0a1. These things have been changing quickly in JupyterLab, especially as we are trying to get things in for 1.0 final, and I know that sometimes our documentation is not quite in sync, so sorry to be unclear.

I'd welcome PRs making this demo repository clearer.

**Comment by ankostis** [comment]
- Finishing my experiment if possible to move the import in `binder/postBuild` with `jupyterlab-1.0.0a8` (probably containing the 5977 fix);
- Will add in any case a note about the pinning in README, and
- make you a PR.

**Comment by ian-r-rose** [comment]
Thanks, @ankostis. Yes, 1.0.0a8 should probably be able to function without the `--name` flag, but I haven't tested it myself yet. I'd like to hear if it works!

**Comment by ian-r-rose** [comment]
@ankostis You will likely also need to update `jupyterlab_server` to its prerelease for your binder instance to work.

**Comment by ankostis** [comment]
~~Thank you, that should make it work!~~
Actually it is not needed, the pre-release `jupyter-server` is fetched transitively.

**Comment by ankostis** [comment]
My apologies if i override this thread, bu i cannot startup the latest jupyterlab.
I have just the pinned pre-release in `requirements.txt` and still i get:
```bash
$ jupyter-repo2docker -E .
...
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/notebookapp.py", line 1760, in start
    super(NotebookApp, self).start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/labapp.py", line 276, in start
    super().start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/labapp.py", line 185, in start
    page_url = config.page_url
AttributeError: 'LabConfig' object has no attribute 'page_url'
```

And it seems that this error is brand new, bc i cannot google anything related.
Am i doing something wrong?
(mybinder gives me the same error)

**Comment by ian-r-rose** [comment]
If you do end up wanting to use `0.35` (i.e., before the subsequent fixes to workspace naming), then [this](https://github.com/pangeo-data/pangeo-example-notebooks/blob/febe8ff2609d0284708115b0a589935d63d919c3/binder/start#L6) repo still has an example for how to get the right workspace name.

**Comment by ian-r-rose** [comment]
As does this repository in [this](https://github.com/ian-r-rose/binder-workspace-demo/tree/0affecdd4ca4fb2bab50630a02713ac61c369cc5) state.

**Comment by ankostis** [comment]
False alarm, it was the command i'm testing causing the problem:

    jupyter lab workspaces import binder/workspace.json

I will search interactively.

**Comment by ankostis** [comment]
> if you do end up wanting to use 0.35 (
> ... this repo still has an example for how to get the right workspace name.

Do you mean  `user/${JUPYTERHUB_USER}` ?

**Comment by ian-r-rose** [comment]
Ooh, that may be a bug in the most recent alpha. Thanks for testing :)

**Comment by ian-r-rose** [comment]
> > if you do end up wanting to use 0.35 (
> > ... this repo still has an example for how to get the right workspace name.
> 
> Do you mean `user/${JUPYTERHUB_USER}` ?

Yes, that line with `sed`. Since jupyterlab/jupyterlab#5977 we should no longer need to include that part of the url in the workspace name, so they should be more portable.

**Comment by ian-r-rose** [comment]
Yep, confirmed that workspaces importing and exporting are broken in the latest alpha.

**Comment by ankostis** [comment]
> Ooh, that may be a bug in the most recent alpha. Thanks for testing :)

Actually,  1.0.0a7 doesn't work either.

**Comment by ian-r-rose** [comment]
I'd recommend using `1.0.0a3`, or the latest stable `0.35` until the PR I just opened fixing the issue lands. Or, if you are feeling adventurous, you can test out jupyterlab/jupyterlab#6585.

To summarize the state of workspace importing:

* On 0.35 you need to manually patch in the workspace name, as per https://github.com/ian-r-rose/binder-workspace-demo/tree/0affecdd4ca4fb2bab50630a02713ac61c369cc5
* On 1.0.0a1-5 you can import using the `--name` argument.
* 1.0.0a7-8 workspace importing is broken.
* On jupyterlab/jupyterlab#6585 you can import workspaces without the `--name` argument.

**Comment by ankostis** [comment]
It should be quite an adventure to use your PR-branch, i guess it cannot be done with a `requirements.txt` alone.  Giving up.

Just to know what is coming, and leave code commented-out for the future...so after 6585, the command would have become simply:

    jupyter lab workspaces import binder/workspace.json

and it could run on build-time, so it will move in `postBiuild`, 
or m i aiming too high?

**Comment by ian-r-rose** [comment]
Yes, that's right. In 0.35 we needed to do the extra logic around getting the right name, once 1.0 final is published that should be enough.

**Comment by stargaser** [comment]
Thank you @ian-r-rose for providing this example. I tried it today and it worked fine, installing Jupyterlab 1.0.1. Perhaps this issue can be closed again?

**Comment by ian-r-rose** [comment]
Good point, thanks @stargaser
